# Generated by Django 3.0.6 on 2020-05-20 15:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_guid', models.CharField(max_length=200)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
